### ISSUE TITLE
Extract data

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#1]
Allow Ken to extract the data. 
Note: For now there can be some manual steps, such as manually importing the data into a google spreadsheet.

**Comment by DaleStan** [comment]
Do you want the "export data" button visible to the canvassers? I'm currently assuming no, so the export button I have now is invisible. The first time you click it, it becomes visible, and the second time it exports the data.

**Comment by KenStanley** [comment]
That makes sense to me. Harmless if they export it, but better not to confuse them.

**Comment by DaleStan** [comment]
The export button can export to Drive or Gmail, to a nearby device via bluetooth, or to a public portion of the Android filesystem (e.g. the Documents folder or a flash drive) via a file manager such as [X-plore](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore).
