### ISSUE TITLE
No mobilizer houses are being found

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#14]
I have ointed the GPS emulator to various locations along Sackman Street, in the 600 block. And VoterMate is not finding any mobilizer houses, though there are plenty of houses on Sackman street in the 600 block.

**Comment by DaleStan** [comment]
The houses listed on the canvass sheet for Sackman St all have a Lat/Lon of [40.773N, 82.542W](https://www.google.com/maps/place/40%C2%B046'22.9%22N+82%C2%B032'29.7%22W/@40.773024,-82.5441449,17z) or [40.770N, 82.535W](https://www.google.com/maps/place/40°46'12.4"N+82°32'06.0"W/@40.7701229,-82.53758,17z). Selecting either of those locations returns results.

The data in the voterDB sheet appears at first glance to be more varied, but still has 43 voters at 40.773N, 82.542W.

**Comment by KenStanley** [comment]
OK I can fix this. But for now Sackman Street appears to be a poor choice for my first canvass. I will try other nearby streets. I do wonder why I screwed up the lat, lon for these. Thanks for the quick response.

**Comment by KenStanley** [comment]
I am marking this as a duplicate of #24 - bad lat,lons.

**Comment by KenStanley** [comment]
This was a lat,lon issue
