### ISSUE TITLE
It would be nice to display the Mobilizer's name after they have been selected 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#21]
Typos happen. So it would be nice to see the mobilizer's name somewhere on one or more screens.

**Comment by KenStanley** [comment]
Actually, it would be nice to be able to change the mobilizer's name. At the first door I knocked on, I thought I was speaking to Daivionna when I was actually talking to Davonna. It might make sense to give them a chance to correct that on the next screen, or just reject the name and enter a different one.

**Comment by DaleStan** [comment]
Closed by 510428b

**Comment by KenStanley** [comment]
This is perfect!
