### ISSUE TITLE
Acknowledging door knocks 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#32]
I have two reasons to want to acknowledge door knocks:

- It would be nice to be able to show canvassers how many doors they have knocked on
- It would be nice to show people which doors they have knocked on
- It might be nice to report which doors have been knocked on so we can prioritize doors that have not been knocked on. 

These will each show up as separate issues, but they all require that we know which doors have been knocked on 

I don't have a preference for how we acknowledge which doors have been knocked on. Here are some ideas:

- Long press and a confirmation on an address on the main page
- Slide right on an address on the main page
- Button on a select household page (i.e. 1 of 30)

**Comment by DaleStan** [comment]
When loading a new turf, should I erase the previous record of knocked doors?
Yes assumes that if a house is listed as part of a loading a new turf, you want someone to knock on that door, but risks losing data that hasn't been exported.
No preserves the data, but makes it impossible to un-knock a door without resetting the entire app and clearing the canvasser name too.
