### ISSUE TITLE
exporting doors knocked on 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#35]
It would be nice to export a fourth file: "doorsKnokcedOn.csv" showing a list of households show doors have been knocked on.

**Comment by DaleStan** [comment]
Do you want it to be just based on when the canvasser taps an address to show the list of voters, or do you want there to be the extra confirmation of selecting one of the voters or a new "No response" button?

**Comment by KenStanley** [comment]
I would prefer some confirmation that they knocked on the door, though if that's harder, your suggestion, if implemented, would make this a lower priority then some of the other issues.
