### ISSUE TITLE
Barack and Michelle Obama aren't showing, nor is Kamala Harris 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#44]
I have given Barack and Michelle an honorary residence at 6 S Park St with Kamala as their neighbor at 8 S Park St, all in Turf 6A-5. Neither are showing up from hedwquarters, nor when I step outside and walk down the block.
I though that the lat,lon was taken from the canvas tab so I updated that. but I am going to try updating the lan, lon in voterDB and then if that doesn't work, I will move on.

**Comment by DaleStan** [comment]
I updated schema.xlsx to show the Obamas' names, and this looks good to me now.
