### ISSUE TITLE
enhanced search 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#47]
I like to use a fuzzy search strategy:

I narrow the set of possible matches by looking for an exact match on first name, last name or street number. 
I then score the matches using whatever information is available:

1. Exact name matches 
2. Partial name matches using a string comparison code (there is presumably a C# string compare package) this will pickup most typos. 
3. Nicknames (I added a sheet called "allNicknames" to the schema database
4. Street name matches - There are a finite number of street names in the Richland county voter database, so if one can check that upon data entry, one can eliminate typos. 

Then show the top five to ten entries on the screen and let the canvasser, and/or mobilizer choose the right one. 

A first name and street number match can catch people who have changed their last name (typically upon marriage) . Last name and street number will often give multiple matches, though rarely more than can be easily displayed on the screen.

Other even more optional fields include: 

1. Age (a guess can help in moving the right person to the top of the list)
2. Middle names or initials - A first name match to a middle name is a strong indicator of a match. As is a last name match to a middle name as some women use their maiden name as their middle name, as in Winifred Swenson Stanley. 
3. Suffix - really not necessary, though it can be quite powerful as people who give you their suffix tend to use it all the time. 
4. Birthdate - I would almost never ask for a birthdate. However, if one rely can't fid someone and the mobilizer is desperate to find htemselves, birthdate is a super strong clue as fewer than 1 in ten thousand voters share the same birthdate, down to the day. 

I would not recommend including any of these at this point, this is just for future reference. 

Note most apps do this poorly. If you fill out more information than you need, all information has to be correct. So you search and then either add more info if you get too many results or less info if you get zero results. I see no excuse for not immediately ignoring excess info when you get no results.

**Comment by DaleStan** [comment]
Typo-resilience in partial name and address matching is supplied by supplying a list of acceptable filters while typing e.g. "mane", and refusing to allow that as a partial name filter. In order to apply a partial filter, you must select one of the displayed options.
It's also supplied by noticing that nobody matches "Christopher", "500", and "Davis", and showing the 13 voters who match two of those three filters.

There's still no typo-resilience in exact name matching, and I forgot about birthdate lookup.

**Comment by DaleStan** [comment]
Oh, also:

I moved the lookup to a separate page (Tap the search icon in the upper right) due to issues with the keyboard covering important parts of the UI.
