### ISSUE TITLE
VoterMate dies if hit Lookup Mobilizer instead of choosing form the drop down 

### ISSUE THREAD

**Issue by KenStanley** [DaleStan/VoterMate#50]
VoterMate dies if hit Lookup Mobilizer (right next to the OH________ ) field 
instead of choosing form the drop down choices. 
It might make sense to get rid of the Look up this Mobilizer option entirely as we have better lookup options.

**Comment by DaleStan** [comment]
I'd like to keep it so we can unambiguously discuss specific voters, e.g. #15 and #45; I'll fix the crashing when the voter ID is not found.

**Comment by DaleStan** [comment]
I just changed how the voter ID text box works, to make it work like the other filters. This removes the "two buttons and you have to touch the right one" behavior.
